[build-system]
# Should be mirrored in requirements-build.txt
requires = [
    "cmake>=3.26",
    "ninja",
    "packaging",
    "setuptools >= 49.4.0",
    "torch == 2.4.0",
    "wheel",
    "jinja2",
]
build-backend = "setuptools.build_meta"
